[package]
name = "xenro45/component"
version = "0.1.0"
description = "A lightweight ECS library"
repository = "https://github.com/xenro45/Component"
realm = "shared"
license = "MIT"
entry = "component.luau"

[dependencies]
